### ISSUE TITLE
Unable to execute query without a transaction

### ISSUE THREAD

**Issue by willnationsdev** [pimbrouwers/Donald#20]
I have to port an app to .NET that connects to a third-party database. I generally have very limited access to the database, given only a view of the data and permission to fetch from that view. Unfortunately, when I used `Donald.DbConn.Async.query`, my request was rejected. After confirming everything else, I found that explicitly *not* using a transaction was the only way the data came back successfully, so it seems that I don't have permission to use those. And when I looked around in the code, there didn't appear to be any way to *not* use a transaction.

Working around it wasn't too bad...

```fsharp
    let getThings () =
        use conn = createConn()
        use cmd = 
            dbCommand conn {
                cmdType CommandType.Text
                cmdText "
                    select * from things
                "
                cmdParam [
                ]
            }
        
        //  DbConn.Async.query Thing.fromReader cmd

        conn.Open()
        use reader = cmd.ExecuteReader()
        let listData =
            [
                while reader.Read() do
                yield Thing.fromReader reader
            ]
        listData
```

...and since it can be "fixed" on my end with just a helper function at no cost to performance, I'm not especially worried about it. But, I figured I'd report it since it was a pain point in the Donald experience (albeit a very small one). I think any attempt to make use of transactions configurable would likely lead to code duplication and/or overcomplication, so I'm not sure any changes are even worth it. If you happen to have any ideas though, then by all means. Otherwise, you can just close this as a `wontfix`. ;-)

**Comment by pimbrouwers** [comment]
Hi Will!!

That is most interesting, I never in a million years would've considered this...

We can easily convert the DbConn module to not use explicit transactions, and cause no backwards compat issues. Which is beatiful. But on the other hand, it means duplicating code, since DbConn uses the functionality of DbTran.

Let me think on this, and perhaps we keep this open for a bit to see if anyone else encounters similar problems.

Out of curiousity are you able to have your permissions extended to create transactions? I see no reason why a DBA (I am one for crying out loud haha) would restrict you from this, outside from the worry that you may not clean it up (commit or rollback). But even that isn't a big concern.

**Comment by willnationsdev** [comment]
@pimbrouwers I could potentially request permission for it, but it's more a matter of the DBA guys having *way* more responsibilities that they are up to their necks in, and I didn't originally want to distract them or create extra work for them if I could help it.

**Comment by jcmrva** [comment]
This is a potential issue for a utility I'm working on. Theoretically every user is a DB admin already, or could get the necessary access, but I can envision scenarios where it's handed out under a much more restricted context.

**Comment by pimbrouwers** [comment]
Sounds good guys. I will make this change to support this scenario.

**Comment by jcmrva** [comment]
Thank you! I'm happy test or help if you need anything.

**Comment by pimbrouwers** [comment]
This has been completed in the 5.1.3 release. Let me know if you guys have any troubles or concerns!
