### ISSUE TITLE
Who is @dysme on the landing page?

### ISSUE THREAD

**Issue by BentTranberg** [pimbrouwers/Donald#38]
Every time I go here, I read about this mysterious @dysme, and I'm thinking should I bother to raise an issue or not. Sooner or later I'm not going to resist the temptation.

Thank you for a wonderful F# library.

**Comment by pimbrouwers** [comment]
A brilliant, mysterious creature known for creating elegant programming languages that developers love!

**Comment by BentTranberg** [comment]
Or @dsyme's undercover identity. I would have made a pull request to fix it, except I don't use Git, so it's a slight hassle for me.

**Comment by pimbrouwers** [comment]
I honestly didn't understand this at first, since the link actually worked. I thought you were just being cheeky haha. But thank you for pointing this out and thank you @dsyme (and @dysme) for the correction. 

Appreciate the love for the library! I've thoroughly enjoyed maintaining it and using it as well!
